version: '3.8'

services:
  mongo:
    image: mongo:4.0
    restart: always
    container_name: mongodb
    environment:
      TZ: 'America/Maceio'
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./mongodb_data:/data/db
    ports:
      - "${MONGO_EXTERNAL_PORT}:27017"

  node:
    image: node:22.11.0
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: node
    restart: always
    working_dir: /home/node/app
    environment:
      TZ: 'America/Maceio'
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./:/home/node/app
    expose:
      - "3000"
    ports:
      - "${NODE_EXTERNAL_PORT}:3000"
    depends_on:
      - mongo
    links:
      - mongo